## Лабораторная работа по курсу "Искусственный интеллект"
## Многослойный персептрон(tensorflow)
| Студент | Аксенов |
|---------|--------|
| Группа  | 6      |


In [13]:
import sys  
from MyFramework import * 
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix


#### MNIST

In [14]:
def change_label(x):
    
    back = np.zeros(10)
    back[x] = 1
    return back

def accuracy(lbl, pred):
    return sum(lbl == pred)/len(lbl)
    

In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train.reshape((60000, 28*28))/255, x_test.reshape((10000, 28*28))/255
y_train, y_test = np.array([change_label(i) for i in y_train]), np.array([change_label(i) for i in y_test])

##### Однослойный перцептрон

In [27]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3, batch_size=None, verbose=0)

In [31]:
print('Доля верный ответов на обучающей выборки = ',accuracy(np.argmax(y_train,1),np.argmax(model.predict(x_train),1)))

Доля верный ответов на обучающей выборки =  0.9251833333333334


In [33]:
print('Доля верный ответов на тестовой выборки = ',accuracy(np.argmax(y_test,1),np.argmax(model.predict(x_test),1)))

Доля верный ответов на тестовой выборки =  0.9222


In [34]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[5773,    1,    7,   10,   10,   30,   34,    7,   50,    1],
       [   1, 6564,   27,   28,    8,   30,    5,   12,   60,    7],
       [  46,   70, 5314,   91,   80,   37,   59,   87,  162,   12],
       [  31,   29,  114, 5482,    9,  221,   24,   54,  125,   42],
       [  20,   31,   26,    6, 5526,    4,   52,   17,   36,  124],
       [  66,   32,   25,  162,   63, 4797,   78,   16,  145,   37],
       [  44,   18,   27,    0,   37,   79, 5671,    2,   40,    0],
       [  23,   37,   69,   27,   53,    9,    2, 5891,   16,  138],
       [  36,  117,   44,  111,   30,  148,   38,   21, 5254,   52],
       [  32,   31,   16,   93,  216,   46,    3,  221,   52, 5239]],
      dtype=int64)

In [35]:
# На тестовой выборке
confusion_matrix(np.argmax(y_test,1),np.argmax(model.predict(x_test),1))

array([[ 966,    0,    1,    1,    0,    4,    5,    2,    1,    0],
       [   0, 1113,    2,    2,    0,    2,    4,    2,   10,    0],
       [  10,   10,  912,   17,    9,    4,   13,   10,   43,    4],
       [   4,    0,   18,  915,    1,   31,    2,   10,   23,    6],
       [   2,    1,    2,    2,  933,    0,   11,    2,   11,   18],
       [  12,    2,    2,   31,   11,  777,   15,    5,   32,    5],
       [  14,    3,    5,    1,    7,   15,  909,    2,    2,    0],
       [   3,    7,   20,    7,    9,    0,    0,  954,    5,   23],
       [   8,    8,    7,   21,    9,   28,    9,   13,  868,    3],
       [  11,    7,    1,   12,   50,    9,    0,   36,    8,  875]],
      dtype=int64)

###### Выводы 
- Переобучение не наблюдается, потому что метрика сильно не отличается на обучающей и тестовой выборке 
- Модель хорошо справилась с задачей 

##### Многослойный перцептрон( С 1 скрытым слоем)

In [37]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3, batch_size=None, verbose=0)

In [38]:
print('Доля верный ответов на обучающей выборки = ',accuracy(np.argmax(y_train,1),np.argmax(model.predict(x_train),1)))

Доля верный ответов на обучающей выборки =  0.9813


In [39]:
print('Доля верный ответов на тестовой выборки = ',accuracy(np.argmax(y_test,1),np.argmax(model.predict(x_test),1)))

Доля верный ответов на тестовой выборки =  0.9719


In [40]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[5841,    3,   16,    0,    7,    2,   14,    1,   15,   24],
       [   1, 6705,    6,    8,    1,    0,    0,    8,   11,    2],
       [   4,   10, 5858,   32,    4,    0,    0,   30,    9,   11],
       [   3,    2,   25, 5974,    1,   39,    2,   14,   36,   35],
       [   1,   11,    6,    0, 5675,    1,    2,    3,    7,  136],
       [   7,    1,    4,   23,    1, 5224,   33,    2,   33,   93],
       [  13,    9,    3,    0,    8,    6, 5867,    1,   10,    1],
       [   1,   16,   13,    8,    4,    0,    0, 6150,    3,   70],
       [   4,   18,   17,   18,    3,    5,   13,    4, 5691,   78],
       [   5,    8,    4,    5,   12,    2,    1,   12,    7, 5893]],
      dtype=int64)

In [41]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[5841,    3,   16,    0,    7,    2,   14,    1,   15,   24],
       [   1, 6705,    6,    8,    1,    0,    0,    8,   11,    2],
       [   4,   10, 5858,   32,    4,    0,    0,   30,    9,   11],
       [   3,    2,   25, 5974,    1,   39,    2,   14,   36,   35],
       [   1,   11,    6,    0, 5675,    1,    2,    3,    7,  136],
       [   7,    1,    4,   23,    1, 5224,   33,    2,   33,   93],
       [  13,    9,    3,    0,    8,    6, 5867,    1,   10,    1],
       [   1,   16,   13,    8,    4,    0,    0, 6150,    3,   70],
       [   4,   18,   17,   18,    3,    5,   13,    4, 5691,   78],
       [   5,    8,    4,    5,   12,    2,    1,   12,    7, 5893]],
      dtype=int64)

###### Выводы 
- Переобучение не наблюдается, потому что метрика сильно не отличается на обучающей и тестовой выборке 
- Модель хорошо справилась с задачей 

#### Dataset FashionMNIST

In [43]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train, x_test = x_train.reshape((60000, 28*28))/255, x_test.reshape((10000, 28*28))/255
y_train, y_test = np.array([change_label(i) for i in y_train]), np.array([change_label(i) for i in y_test])

In [44]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3, batch_size=None, verbose=0)

In [45]:
print('Доля верный ответов на обучающей выборки = ',accuracy(np.argmax(y_train,1),np.argmax(model.predict(x_train),1)))

Доля верный ответов на обучающей выборки =  0.88445


In [46]:
print('Доля верный ответов на тестовой выборки = ',accuracy(np.argmax(y_test,1),np.argmax(model.predict(x_test),1)))

Доля верный ответов на тестовой выборки =  0.8655


In [47]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[5602,    9,   66,  164,   17,    4,  110,    0,   28,    0],
       [  14, 5873,    3,   95,    6,    0,    7,    0,    2,    0],
       [ 156,    8, 5177,   79,  478,    1,   86,    0,   15,    0],
       [ 178,   33,   29, 5449,  256,    1,   37,    0,   17,    0],
       [  12,    9,  723,  151, 4980,    0,  107,    0,   18,    0],
       [   0,    0,    1,    1,    0, 5851,    0,  118,    2,   27],
       [1499,    6,  855,  158,  637,    2, 2798,    1,   44,    0],
       [   0,    0,    0,    0,    0,   83,    0, 5723,    2,  192],
       [  47,    1,   21,   18,   31,   21,    4,   15, 5840,    2],
       [   1,    0,    0,    0,    0,   66,    0,  158,    1, 5774]],
      dtype=int64)

In [48]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[5602,    9,   66,  164,   17,    4,  110,    0,   28,    0],
       [  14, 5873,    3,   95,    6,    0,    7,    0,    2,    0],
       [ 156,    8, 5177,   79,  478,    1,   86,    0,   15,    0],
       [ 178,   33,   29, 5449,  256,    1,   37,    0,   17,    0],
       [  12,    9,  723,  151, 4980,    0,  107,    0,   18,    0],
       [   0,    0,    1,    1,    0, 5851,    0,  118,    2,   27],
       [1499,    6,  855,  158,  637,    2, 2798,    1,   44,    0],
       [   0,    0,    0,    0,    0,   83,    0, 5723,    2,  192],
       [  47,    1,   21,   18,   31,   21,    4,   15, 5840,    2],
       [   1,    0,    0,    0,    0,   66,    0,  158,    1, 5774]],
      dtype=int64)

###### Выводы 
- Переобучение не наблюдается, потому что метрика сильно не отличается на обучающей и тестовой выборке 
- Модель хорошо справилась с задачей 

#### Dataset CIFAR-10

In [61]:
cifar10 = tf.keras.datasets.cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train.reshape((50000, 32*32*3))/255, x_test.reshape((10000, 32*32*3))/255
y_train, y_test = np.array([change_label(i) for i in y_train]), np.array([change_label(i) for i in y_test])

In [62]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(256*10,activation='relu'))
model.add(tf.keras.layers.Dense(128*10,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3, batch_size=None, verbose=0)

In [63]:
print('Доля верный ответов на обучающей выборки = ',accuracy(np.argmax(y_train,1),np.argmax(model.predict(x_train),1)))

Доля верный ответов на обучающей выборки =  0.45332


In [64]:
print('Доля верный ответов на тестовой выборки = ',accuracy(np.argmax(y_test,1),np.argmax(model.predict(x_test),1)))

Доля верный ответов на тестовой выборки =  0.4505


In [65]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[1939,  243,  680,  186,  304,   61,  102,  139,  957,  389],
       [ 143, 2739,   71,  191,  128,   86,   71,  120,  519,  932],
       [ 260,  135, 1952,  369,  893,  195,  688,  192,  171,  145],
       [  89,  135,  618, 1790,  429,  495,  823,  156,  187,  278],
       [ 192,   80,  934,  244, 2194,   99,  685,  265,  167,  140],
       [  65,  105,  769, 1248,  440, 1194,  675,  196,  158,  150],
       [  36,   88,  485,  426,  759,  138, 2757,   77,  104,  130],
       [ 157,  104,  636,  293,  921,  211,  281, 1933,  111,  353],
       [ 352,  235,  159,  197,  157,   64,   31,   51, 3341,  413],
       [ 175,  780,   73,  212,  127,   58,  120,  144,  484, 2827]],
      dtype=int64)

In [66]:
# На обучающей выборке
confusion_matrix(np.argmax(y_train,1),np.argmax(model.predict(x_train),1))

array([[1939,  243,  680,  186,  304,   61,  102,  139,  957,  389],
       [ 143, 2739,   71,  191,  128,   86,   71,  120,  519,  932],
       [ 260,  135, 1952,  369,  893,  195,  688,  192,  171,  145],
       [  89,  135,  618, 1790,  429,  495,  823,  156,  187,  278],
       [ 192,   80,  934,  244, 2194,   99,  685,  265,  167,  140],
       [  65,  105,  769, 1248,  440, 1194,  675,  196,  158,  150],
       [  36,   88,  485,  426,  759,  138, 2757,   77,  104,  130],
       [ 157,  104,  636,  293,  921,  211,  281, 1933,  111,  353],
       [ 352,  235,  159,  197,  157,   64,   31,   51, 3341,  413],
       [ 175,  780,   73,  212,  127,   58,  120,  144,  484, 2827]],
      dtype=int64)

###### Выводы 
- Переобучение не наблюдается, потому что метрика сильно не отличается на обучающей и тестовой выборке 
- Модель не так хорошо справилась с задачей, как с прошлыми задачами 
